# Numpy Exercise for AI 240  - 10459          

Instructor- Dr. Uma Gajendragadkar

### Exercise 1.1 - If Numpy is not already installed then please install Numpy using below instruction
!pip install Numpy      

### Exercise 1.2 # Import Numpy package using below instruction 
import numpy as np

### Exercise 1.3 ## Example Usage Read below example and execute the cell

data = np.array([1,2,3,4,5])

print(data)

print(len(data))

print(type(data))

print(data.shape)

### Exercise 1.4 Do all exercises from Lecture slides. Refer slides shared after the lecture.

### Exercise 1.5 Searching Arrays - find method of numpy to search an element in array - You can google for the method

Find the indexes where the value is 9:


arr = np.array([3, 2, 14, 9, 10, 12])

### Exercise 1.6 Join two arrays given below and print the result.

arr1 = np.array([9, 5, 8])

arr2 = np.array([55, 89, 76])

### Save and submit your notebook in your Github account.

In [1]:
!pip install Numpy

In [3]:
import numpy as np

In [5]:
data = np.array([1,2,3,4,5])

print(data)

print(len(data))

print(type(data))

print(data.shape)

[1 2 3 4 5]
5
<class 'numpy.ndarray'>
(5,)


In [7]:
arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [9]:
arr2D = np.array([[10, 20, 30] , [40, 50, 60]])
print(arr2D)

[[10 20 30]
 [40 50 60]]


In [13]:
print(arr[0])

10


In [15]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr1[1:5])

[2 3 4 5]


In [19]:
arr2 = np.array([30, 20, 40, 10])
print(np.sort(arr2))

[10 20 30 40]


In [21]:
arr3 = np.array(['kiwi', 'berry', 'pear'])
print(np.sort(arr3))

['berry' 'kiwi' 'pear']


In [25]:
arr1_5 = np.array([3, 2, 14, 9, 10, 12])
x = np.where(arr1_5 == 9)
print(x)

(array([3], dtype=int64),)


In [33]:
arr1_6 = np.array([9, 5, 8])

arr2_6 = np.array([55, 89, 76])

y = np.concatenate((arr1_6, arr2_6), axis = 0)
print(y)

[ 9  5  8 55 89 76]
